= RR Decoder Database Application

== Introduction
The RR Decoder Database application is a tool that reads the roster.xml files created by DecoderPro, breaks them
apart and stores them in a relational database (the database software is H2, a pure Java tool included with
this tool). The tool provides several ways to view the data including severals ways to view CV values (and
compare those values between locomotives), a view of the labels applied to Functions Keys and Speed profiles
(if you are using those).

== Installation

The Software is distributed in a zip file including all the needed required software (except Java itself). You
need a Java version 11 or later to run it (the same as JMRI). Unzip the the software into an empty directory.
It will create a directory called "decoderDB", with two directories inside "bin" 
and "lib". In the bin directory are two files: "app" and "app.bat". The "app" file
is for Unix or Max, while the "app.bat" is for Windows.
There are several ways to run the application:
You can open a command line (in Unix, a shell, for Mac, a Terminal, or
for Windows, a command line (cmd.exe), and then make the current directory the
bin directory where you unzipped the software. Then type "app.bat" for Windows or
"./app" for Mac or Unix.
A second way to run the application is to double-click the "app" or "app.bat" file.

=== First Usage
The first time you run the application you will need to provide some values to be used for the database.
These values will be saved, so you will only need to provide them once. You can change them later, if you want.

The database requires a userid and password. 
The first use of the database will setup the userid and password. 
That means that you can choose your own userid and password. 
The password will *NOT* be stored securely, so don't reuse any of your other
passwords. This database will not be storing any financial or other critical
data, so the security of the password is not important.

The database is specified by entering a URL specifiying the name, type and location of the database. While you could enter the URL directly, the easiest way is 
to select the "Location" selection and then use the "Choose Location" button
to open a File Chooser window. Navigate to an appropriate directory (a good 
choice would be the directory which contains the "decoderDB" directory created
when you unzipped the application.

You will need to specify to additonal items beyond the location of the database:
the name of the database, and the schema to use within the database. 
Choose a value for each. "decoder" will work well.

When all values have been entered, the "Save new settings" button will be enabled.
Press that button and you will not need to reenter the values (they will be saved
in a file in a directory in your home directory. 

Successfully saving the values will open the main "Model Railroad Decoder Database App". At this point you will have no entries in the main window.

=== The Main window

The main window shows a list of all rosters that have been imported.
The application will not look for rosters -- you will need to import them 
into the application.

==== Importing a roster.

Open the "File" menu and choose "Import". You use the shortcut of pressing ALT-I
(or Cmd-I for UNIX or Mac).
This will open a File Chooser window. 
You will need to select the "roster.xml" for the JMRI profile you would 
like to import.
If you aren't using JMRI profiles, or have only one profile, it is most likely
to be found in the JMRI directory in your home directory.
For Windows users this is usually called "JMRI" and the default railroad name is
"My_JMRI_Railroad.jmri" For Unix and Mac this directory is usually "jmri" and is
hidden (but the Widow will show hidden files). If the JMRI profile has
no decoders saved, there may not be a "roster.xml" file. Select the "roster.xml" 
file and click on the "Open" button. This will import the data in the roster 
(you may see a progress window, showing the progress of the import).

Once you have imported one or more rosters, you will see the list of 
rosters you have imported.

The roster list will show six columns of data:

. ID - This an arbitrary number generated by the database to refence this entry.
. System - The name of the machine where the import was run. If you are using a local database, this will be a constant and you can ignore it. It you using 
a network based database this will show the machine where you imported the roster.
If you want to update the definitions, you should import again, from the same machine.
. #Decoders - The number of decoders found in that roster.
. Full Path - The complete path to the roster.xml that was imported.
. File Date - The date and time of the roster.xml.
. Import Date - The date and time the roster was imported.
. Updated - The date and time the roster was last updated.

==== Window Actions

The actions within the window are common to all windows.

You may move or re-size the windows. If you do, the location and size
will be rembered the next time you use the program. If part of the screen
is not visible, simple resize the window to view the entire window.

Selection of one or more entries is commonly done with the mouse.
To select one roster, simply move the mouse pointer to it and click.
To expand the selection to multiple entries, hold down the shift key
while you click on another entry. That will add that entry
and all entries between it and the original entry. If you hold down
the Control key while you click it will add (or subtract) that single entry.
Control-clicking an entry will reverse the selection state of that entry.

Several menu actions will depend on whether or not a row is selected.
Those actions will be disabled until one or more rows are selected. The state of
the action will be visible when you pull down a menu (disabled actions are grayed out).

Clicking on a header entry will sort the entries by that column. Clicking
again on that entry will sort the rows in the reverse order by that column.
Position the mouse pointer on a column header and drag that header to a new
position to reposition that column.
Position the mouse pointer in the header line on the line between two columns
and drag left or right to resize that columns.
When you move or resize a column, that action will be saved and the column sizes
and positions will be restored when you restart the program.


==== Importing Details
When one or more rosters have been selected, the "Import Details" menu choice will be
enabled. At this point, it would be best to defer importing details until you have
opened the roster and selected a small number of decoders. Importing the details
can take a *VERY* long time, so it's best to do it in small increments, a few decoders at a time

==== Closing the Program
Choose "File" "Close" (or Alt-C) to end the program. In other windows, this action
will only end the current window.

==== Settings -- Edit
This menu choice will allow you to change your initial selection of Database name, location,
userid and password. Those values will be remembered each time to start the program. You
may safely ignore this menu unless you want to switch to a different database.

==== View -- All
The "View" "All Decoders" menu choice will be bring up a window containing every decoder
from all rosters which have been imported.

==== View -- Selected Decoders
The "View Selected Decoders" menu choice will only be enabled if you have selected one or more
rosters. When you select this menu item, it will bring up a window with all decoders from
every roster that has been selected.

=== Help
At the moment, the Help menu items do nothing.


=== The Decoder Window
The Decoder Window opens when either View All or View Selected is chosen in the main window.
The window shows all decoders contained in the selected roster(s).
The columns can be rearranged by dragging column heads to new positions.
The sizes of columns can be adjusted by dragging the bar in the column heads between columns
to the left or the right. Both of these changes will be saved and restored the
next time you show this window.

==== Decoder View Columns

* ID - An arbitrary number assigned by the database to represent this decoder. It has
no particular meaning, but if you want to restore the original order, simply sort by this column.

* RosterId -- the database assigned identifier of the roster from which this entry came.
If you selected multiple rosters to view (or chose to view ALL rosters), use this value to
distinguish where this decoder entry came from.

* Address is the DCC address assigned to this decoder. It could be a long address or a short
address (DecoderPro does not indicate which in the roster, but it can be significant to
your command station/throttle combination if you want to select it).

* Speeds? - shows "Yes" if this entry has a speed profile associated with it.
The Speed Profile is generated by PanelPro, by selecting "Speed Profiling" from the PanelPro Roster menu.
PanelPro can show the current speed profile from that window, or
use that same window to generate a speed profile. 
This column shows you if a decoder has had a speed profile generated.
If there is a speed profile, you can use this tool to view it, either as a graph,
or just as a series of numbers.

* Details? - have the details for the decoder have been read and added to the database?
When you first import the roster.xml, the program only reads the roster.xml file.
There is an additional file specific to this decoder
(the name is contained in the next column), that has the details
of the settings for the decoder. Reading that file can take a long time
(from seconds to several minutes), depending on the size of the file.
Because of that potentially long delay, those files are not read until you specifically
request that they be read. Select one or more decoders and choose File, Import Detail
(or press Alt-I) to read the files belonging to the selected decoders.

* XML File - the name of the file containing the details of the deccoder.

* Road Name (and Road Number) - the values entered in these fields when the XML file was
created (or last modified).

* Manufacturer - the manufacturer of the decoder.

* Decoder Family - The subset of the manufacturers decoders, assigned by the decoder 
selection when the entry was first created.

* Decoder Model - The specific decoder found, from the original DecoderPro creation
of a decoder entry.

* Owner - The owner of the locomotive.

* Updated - when the roster.xml entry was last read.

* Imported - when the roster.xml entry was first read.

* Details Read - when the the details were last read from the XML file listed in 
the XML File column (or blank if the details have not yet been read).

==== Decoder View Menu Items

* File - Import Details - only enabled if one or more decoders are
selected. Read the complete XML file for the selected decoder(s).
This can take some time, depending on the complexity of the
individual decoder. During the process, a Progress dialog
will show how many decoders have been process, and show
the progress of reading each decoder XML file.

* FIle - Print -












