= RR Decoder Database Application

== Introduction
The RR Decoder Database application is a tool that reads the roster.xml files created by DecoderPro, breaks them
apart and stores them in a relational database (the database software is H2, a pure Java tool included with
this tool). The tool provides several ways to view the data including severals ways to view CV values (and
compare those values between locomotives), a view of the labels applied to Functions Keys and Speed profiles
(if you are using those).

== Installation

The Software is distributed in a zip file including all the needed required software (except Java itself). You
need a Java version 11 or later to run it (the same as JMRI). Unzip the the software into an empty directory.
It will create several directories (including one called "app"). Inside the app folder, you will find a
file called "app.bat" and another simply called "app". The ".bat" file is for Windows and the other for Mac and
Unix (untested). Double click on the app.bat file and it will run the application.

=== First Usage
The first time you run the application you will need to provide some values to be used for the database.
These values will be saved, so you will only need to provide them once. You can change them later, if you want
(though that will force you to reimport your date).

The database requires a userid and password. Since the database will be created after you have entered all
the values, the userid id and password are your choice (the first usage sets them). The values are saved
in an insecure manner so don't repeat these from another application. Security is not an issue with this
application because it's only accessible from the local machine and the database doesn't hold any
financially significant data.

The database can be specified either with the full URL, containing all the parts, or be specifying each
part individually. If you enter the parts, the full URL will be automatically populated and stored.
The three parts required are: database location, name and the schema for the decoder data.
The easiest method to select the location is to use the "Choose Location" button and select an empty
directory.
The database name is flexible, but must be at least three characters long, begin with a letter and
contain only letters, numbers and possibly underscores.
The final choice is for the schema to use for the tables in the database (I used "decoder" for mine).

Once all the values have been entered, the "Save New Settings" button will be enabled. When you click on
that button, all the settings will be validated and, if all are good, the values will be saved and you
will see the main window.

=== The Main window

The main window shows a list of all rosters that have been imported (the
ones the program knows about).
The list will be empty until you import a roster.
If there are roster entries present, you may select one or more.
The

==== Window Actions

The actions within the window are common to all windows.

Selection of one or more entries is commonly done with the mouse.
To select one roster, simply move the mouse pointer to it and click.
To expand the selection to multiple entries, hold down the shift key
while you click on another entry. That will add that entry
and all entries between it and the original entry. If you hold down
the Control key while you click it will add (or subtract) that single entry.
Control-clicking an entry will reverse the selection state of that entry.

Several menu actions will depend on whether or not a row is selected.
Those actions will be disabled until one or more rows are selected. The state of
the action will be visible when you pull down a menu (disabled actions are grayed out).

Clicking on a header entry will sort the entries by that column. Clicking
again on that entry will sort the rows in the reverse order by that column.
Position the mouse pointer on a column header and drag that header to a new
position to reposition that column.
Position the mouse pointer in the header line on the line between two columns
and drag left or right to resize that columns.
When you move or resize a column, that action will be saved and the column sizes
and positions will be restored when you restart the program.

==== The Main Window Contents

Each row in the main window is roster that has been imported. The "Id" column is
the number which has been assigned by the database to this roster. It has no
importance other than to identify the roster to the database.

The "System" column contains the name of the PC which created this row. If your
database is not located on a network, the value will always be the same.

The "File Date" is the date assigned by the operating system to the roster.xml file.
This usually represented the data the file was last modified.

The "Import Date" is the date and time this file was last imported. If you know you have
used DecoderPro to change the values in a decoder, you should probably Import this roster
again.

The "# Decoders" column shows the number of decoders that are contained in that roster.
It is not uncommon to see an entry showing zero. This is often the case if that
profile is used for OperationsPro.

The "Full Path" shows where roster.xml file is located. If you have multiple rosters in
your database, this is probably the best way to identify the one you want.

==== Importing a Roster
Choose "File Import" (or Alt-I) to import a roster. That will bring up a
dialog which will allow you to select a "roster.xml" That file (generated by
DecoderPro) contains a listing of all the decoders that have been either
programmed by DecoderPro or imported into DecoderPro.
When the dialog opens, it show the contents of your "Documents" folder. You
will need to navigate to the "roster.xml" which is normally found
within the folder defined by the profile (you may have chosen to locate
it elsewhere, such as on a network drive, or in a DropBox folder).
If the profile is in a default location, you should
navigate to the "Users" folder and within that you should find a folder
representing you (the current user). Within that folder will be a "JMRI"
folder and within that will be one or more JMRI Profile folders (again, you
may have chosen to place them elsewhere). If there is a Roster in that location,
the diaglog will show a "roster.xml". Select that file and click on "Open" to import that
roster. If you don't want to import any roster at this time, simply click on
cancel to cancel the import.

==== Importing Details
When one or more rosters have been selected, the "Import Details" menu choice will be
enabled. At this point, it would be best to defer importing details until you have
opened the roster and selected a small number of decoders. Importing the details
can take a *VERY* long time, so it's best to do it in small increments a few decoders at a time

==== Closing the Program
Choose "File" "Close" (or Alt-C) to end the program. In other windows, this action
will only end the current window.

==== Settings -- Edit
This menu choice will allow you to change your initial selection of Database name, location,
userid and password. Those values will be remembered each time to start the program. You
may safely ignore this menu unless you want to switch to a different database.

==== View -- All
The "View" "All Decoders" menu choice will be bring up a window containing every decoder
from all rosters which have been imported.

==== View -- Selected Decoders
The "View Selected Decoders" menu choice will only be enabled if you have selected one or more
rosters. When you select this menu item, it will bring up a window with all decoders from
every roster that has been selected.

=== Help
At the moment, the Help menu items do nothing.


=== The Decoder Window
The Decoder Window opens when either View All or View Selected is chosen in the main window.
The window shows all decoders contained in the selected roster(s) -- unless you chose to filter
out out some decoders based on their characteristics.
The columns can be rearranged by dragging column heads to new positions.
The sizes of columns can be adjusted by dragging the bar in the column heads between columns
to the left or the right. Both of these changes will be saved and restored the
next time you show this window  (the view filters will not be restored).

==== The columns
The Id is a an arbitrary number assigned by the database to represent this decoder. It has
no particular meaning, but if you want to restore the original order, simply sort by this column.

RosterId is database assigned identifier of the roster from which this entry came.
If you selected multiple rosters to view (or chose to view ALL rosters), use this value to
distinguish where this decoder entry came from.

Address is the DCC address assigned to this decoder. It could be a long address or a short
address (DecoderPro does not indicate which in the roster, but it can be significant to
your command station/throttle combination if you want to select it).

The "Speeds?" column shows whether or not this entry also has a speed profile associated with it.
The Speed Profile is generated by PanelPro, by selected "Speed Profiling" from the Roster menu.
You can select a locomotive and view the current profile from that window.
Use that same window to generate a speed profile.
The RrDecoder tool shows you if a decoder has had a speed profile generated.

The "Details?" column shows if the details for the decoder have been read and added to the database.
When you first import the roster.xml, the program only reads that one file.
There is an additional file specific to this decoder
(the name is contained in the next column), that has the details
of the settings for the decoder. Reading that file can take a long time
(from seconds to several minutes), depending on the size of the file.
Because of that potentially long delay, those files are not read until you specifically
request that they be read. Select one or more decoders and choose File, Import Detail
(or press Alt-I) to read the files belonging to the selected decoders.

The XML File column contains the name of the file containing the details of the deccoder.

Road Name (and Road Number) are the values entered in these fields when the XML file was
created (or last modified).






