
CREATE TABLE IF NOT EXISTS
    roster
    (
        id      INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT primaryKey PRIMARY KEY,
        entered     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
        fullpath    VARCHAR(256) DEFAULT '' NOT NULL ,
        dateUpdated TIMESTAMP,
        fileDate    TIMESTAMP,
        systemName  VARCHAR(64) DEFAULT '' NOT NULL
    );
CREATE UNIQUE INDEX IF NOT EXISTS
    roster_IDX1
ON
    roster
    (
        systemName,
        fullpath
    );
CREATE TABLE IF NOT EXISTS
    decoderType
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT decoderType_primaryKey
        PRIMARY KEY,
        decoderFamily VARCHAR(256),
        decoderModel  VARCHAR(256),
        dateUpdated   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    );
CREATE UNIQUE INDEX IF NOT EXISTS
    Decoder_IDX1
ON
    decoderType
    (
        decoderFamily,
        decoderModel
    );
CREATE TABLE IF NOT EXISTS
    decoder
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT decoder_primaryKey PRIMARY
        KEY,
        decoderID      VARCHAR(256) CONSTRAINT decoderID_null NOT NULL,
        fileName       VARCHAR(256) CONSTRAINT decoder_fileName NOT NULL,
        roadNumber     VARCHAR(256),
        roadName       VARCHAR(256),
        manufacturer   VARCHAR(256),
        owner          VARCHAR(256),
        model          VARCHAR(256),
        dccaddress     VARCHAR(256),
        manufacturerID VARCHAR(256),
        productid      VARCHAR(256),
        decoderDate    TIMESTAMP,
        dateImported   TIMESTAMP,
        dateUpdated    TIMESTAMP,
        detailTime     TIMESTAMP,
        decoderTypeID  INTEGER NOT NULL CONSTRAINT loco_decoder REFERENCES decoderType(id)
        ON
DELETE
    RESTRICT,
    rosterID INTEGER NOT NULL CONSTRAINT loco_roster REFERENCES roster(id)
ON
DELETE
    CASCADE,
    cvVersion INT NOT NULL DEFAULT 0,
    labelVersion INT NOT NULL DEFAULT 0,
    functionVersion INT NOT NULL DEFAULT 0,
    keyVersion INT NOT NULL DEFAULT 0,
    Shunt VARCHAR(16)
    );
CREATE TABLE IF NOT EXISTS
    functionLabels
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT func_labl_primaryKey
        PRIMARY KEY,
        decoderID INTEGER NOT NULL,
        functionNumber VARCHAR(16) NOT NULL,
        functionLabel  VARCHAR(255) NOT NULL,
        locked BOOLEAN,
        Label_Version INTEGER,
        CONSTRAINT Func_Labl_decoder FOREIGN KEY (decoderID) REFERENCES decoder(id) ON
DELETE
    CASCADE,
    CONSTRAINT lab_unique UNIQUE (decoderid, functionnumber)
        );
CREATE TABLE
    label_versions
    (
        decoderid      INTEGER NOT NULL,
        version_number INTEGER,
        version_time   TIMESTAMP NOT NULL,
        CONSTRAINT label_ver_foreign FOREIGN KEY (decoderid) REFERENCES decoder (id) ON
        DELETE CASCADE,
        CONSTRAINT label_ver_primary PRIMARY KEY (decoderid, version_number)
    );
    CREATE TABLE
    saved_Labels
(
    decoderid      INTEGER NOT NULL,
    functionnumber CHARACTER VARYING(16) NOT NULL,
    version_number INTEGER NOT NULL,
    saved_label    CHARACTER VARYING(255),
    locked         BOOLEAN,
    CONSTRAINT svd_labs_primary PRIMARY KEY (decoderid, functionnumber, version_number),
    CONSTRAINT svd_labs_foreign FOREIGN KEY (decoderid, functionnumber) REFERENCES
        functionlabels (decoderid, functionnumber) ON
        DELETE
        CASCADE
);
        
CREATE TABLE IF NOT EXISTS
    SpeedProfile
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT speed_profile_primaryKey
        PRIMARY KEY,
        decoderID INTEGER NOT NULL CONSTRAINT speed_profile_decoder REFERENCES decoder(id)
        ON
DELETE
    CASCADE,
    step INTEGER,
    forward DOUBLE,
    reverse DOUBLE
    );
CREATE TABLE IF NOT EXISTS
    KeyValues
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT key_value_primaryKey
        PRIMARY KEY,
        decoderID INTEGER NOT NULL CONSTRAINT key_value_decoder REFERENCES decoder(id) ON
DELETE
    CASCADE,
    Pair_Key   VARCHAR(255),
    Pair_value VARCHAR(255),
    key_version INTEGER,
    CONSTRAINT key_unique UNIQUE (decoderid, pair_key)
    );
    
CREATE TABLE
    saved_keys
(
    decoderId      INTEGER NOT NULL,
    pair_key       CHARACTER VARYING(255) NOT NULL,
    version_number INTEGER NOT NULL,
    CONSTRAINT saved_keys_unique UNIQUE (decoderid, pair_key, version_number),
    CONSTRAINT saved_keys_primary PRIMARY KEY (decoderid, pair_key, version_number),
    CONSTRAINT saved_keys_foreign FOREIGN KEY (decoderId, pair_key) REFERENCES keyvalues
        (decoderid, pair_key) ON
        DELETE
        CASCADE
);

CREATE TABLE
    key_versions
(
    decoderid    INTEGER NOT NULL,  
    version      INTEGER NOT NULL,
    version_time TIMESTAMP NOT NULL,
    CONSTRAINT key_ver_unique UNIQUE (decoderid, version),
    CONSTRAINT key_ver_primary PRIMARY KEY (decoderid, version),
    CONSTRAINT key_ver_foreign FOREIGN KEY (decoderid) REFERENCES decoder
        (id) ON
        DELETE
        CASCADE
);

CREATE TABLE IF NOT EXISTS
    DecoderDef
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT dec_def_primaryKey PRIMARY 
        KEY,
        decoderID INTEGER NOT NULL CONSTRAINT dec_def_decoder REFERENCES decoder(id) ON
DELETE
    CASCADE,
    varValue VARCHAR(255),
    item     VARCHAR(255)
    );
CREATE TABLE IF NOT EXISTS
    CVValues
    (
        id   INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cv_primaryKey PRIMARY KEY,
        decoderID INTEGER NOT NULL CONSTRAINT cv_decoder REFERENCES decoder(id) ON
DELETE
    CASCADE,
    cvValue VARCHAR(255),
    cvNumber   VARCHAR(255) NOT NULL,
    CONSTRAINT cvVal_uniq UNIQUE (decoderId, CvNumber)
    );
CREATE TABLE 
    cv_versions
    (
        decoderId  INT NOT NULL,
        cvVersion  INT NOT NULL,
        changeTIme TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
        CONSTRAINT cv_ver_uni UNIQUE (decoderId, cvVersion),
        CONSTRAINT cv_ver_pri_key PRIMARY KEY (decoderId, cvVersion),
        CONSTRAINT cv_ver_for_cvNumber FOREIGN KEY (decoderId) REFERENCES decoder (id) ON 
DELETE 
    CASCADE
    );
    CREATE TABLE savedCVvals
(
    decoderId INT   NOT NULL ,
    cvNumber  VARCHAR(255) NOT NULL ,
    version   INT   NOT NULL,
    savedVal  VARCHAR(255) ,
    CONSTRAINT svd_val_uni UNIQUE (decoderId, cvNumber, version),
    CONSTRAINT svd_val_for_parent FOREIGN KEY (decoderId, cvNumber) REFERENCES CVVALUES (decoderId, cvNumber)
);

CREATE TABLE IF NOT EXISTS
    DB_VERSION    
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT version_def_primaryKey PRIMARY KEY,
	major INTEGER NOT NULL,
        minor INTEGER NOT NULL,
        table_count INTEGER NULL
    );
INSERT INTO
    DB_VERSION
        (id, major, minor, table_count) VALUES ( 1, 1, 3, 12 )
;
