CREATE USER rrdec password 'rrdecpw';
CREATE schema rrdec;
GRANT ALTER ANY schema TO rrdec;
CREATE TABLE
    rrdec.roster
    (
        id      INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT primaryKey PRIMARY KEY,
        entered     TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL ,
        fullpath    VARCHAR(256) DEFAULT '' NOT NULL ,
        dateUpdated TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL ,
        systemName  VARCHAR(64) DEFAULT '' NOT NULL
    );
CREATE UNIQUE INDEX 
    rrdec.roster_IDX1
ON
    rrdec.roster
    (
        systemName,
        fullpath
    );
CREATE TABLE
    rrdec.decoder
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT decoder_primaryKey PRIMARY 
        KEY,
        decoderFamily VARCHAR(256),
        decoderModel  VARCHAR(256),
        dateUpdated   TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
    );
CREATE UNIQUE INDEX 
    rrdec.Decoder_IDX1
ON
    rrdec.decoder
    (
        decoderFamily,
        decoderModel
    );
CREATE TABLE
    rrdec.locomotive
    (
        id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT loco_primaryKey PRIMARY 
        KEY,
        locoID         VARCHAR(256) CONSTRAINT locoID_null NOT NULL,
        fileName       VARCHAR(256) CONSTRAINT loco_fileName NOT NULL,
        roadNumber     VARCHAR(256),
        roadName       VARCHAR(256),
        manufacturer   VARCHAR(256),
        owner          VARCHAR(256),
        model          VARCHAR(256),
        dccaddress     VARCHAR(256),
        manufacturerID VARCHAR(256),
        productid      VARCHAR(256),
        dateUpdated    TIMESTAMP CONSTRAINT loco_TS NOT NULL,
        decoderID      INTEGER NOT NULL CONSTRAINT loco_decoder REFERENCES rrdec.decoder(id) ON 
DELETE 
    RESTRICT,
    rosterID INTEGER NOT NULL CONSTRAINT loco_roster REFERENCES rrdec.roster(id) 
ON 
DELETE 
    CASCADE
    );

    