-- generated by Jailer 17.1.4, Fri Jul 17 15:32:39 EDT 2026 from JScot@Charlie

-- Extraction Model:  TESTSCHEMA.DECODER where id in (143, 144, 145, 146, 1, 2, 3) (C:\Users\JScot\.jailer\extractionmodel\by-example\SbE-DECODER-10-42-12-911.jm)
--                    Union TESTSCHEMA.CVVALUES where T.ID in ( Select T_SUB.ID From TESTSCHEMA.CVVALUES T_SUB Where exists ( select * from TESTSCHEMA.CV_DIFF b where b.CVNUMBER = T_SUB.CVNUMBER and b.DECODERID = T_SUB.DECODERID ) )
--                    Union TESTSCHEMA.CVVALUES where decoderid in (143, 144, 145, 146)
--                          limit 100
--                    Union TESTSCHEMA.CV_DIFF where decoderid in (143, 144, 145, 146)
--                    Union TESTSCHEMA.FUNCTIONLABELS where decoderid in (143, 144, 145, 146)
--                    Union TESTSCHEMA.KEYVALUES where decoderid in (143, 144, 145, 146)
--                    Union TESTSCHEMA.LABEL_DIFF where decoderid in (143, 144, 145, 146)
--                    Union TESTSCHEMA.LABEL_VERSIONS where decoderid in (143, 144, 145, 146)
-- Source DBMS:       H2
-- Target DBMS:       H2
-- Database URL:      jdbc:h2:file:c:\Projects\decodder3\database;AUTO_SERVER=TRUE;
-- Database User:     rruser

-- Exported Rows:     177
--    CVVALUES                        104 
--    CV_DIFF                          11 
--    CV_VERSIONS                       7 
--    DECODER                           7 
--    DECODERTYPE                       6 
--    FUNCTIONLABELS                   10 
--    KEYVALUES                         3 
--    LABEL_DIFF                       19 
--    LABEL_VERSIONS                    8 
--    ROSTER                            2 

-- sync

Insert into DECODERTYPE(ID, DECODERFAMILY, DECODERMODEL, DATEUPDATED) values 
 (1, 'WOW Steam Sound Set 4.6', 'WOW Steam 121 SS4.6', '2026-06-21 15:54:13.361725'), 
 (2, 'Paragon 3', 'Diesel', '2026-06-21 15:54:13.492175'), 
 (3, 'Paragon 3', 'Rolling Thunder', '2026-06-21 15:54:13.566951'), 
 (37, 'Economy Series 6 with FX3, silent', 'DH126PS', '2026-06-25 18:22:42.474638'), 
 (38, 'WOW Steam Sound Set 4', 'WOW Steam 121 SS4', '2026-06-25 18:27:19.134346'), 
 (4, 'ESU LokSound 5', 'LokSound 5', '2026-06-21 15:54:13.577461');
Insert into ROSTER(ID, ENTERED, FULLPATH, DATEUPDATED, FILEDATE, SYSTEMNAME) values 
 (1, '2026-06-21 15:54:13.206933', 'C:\Users\JScot\Dropbox\Apps\JMRIfolder\Pennsy_West\roster.xml', '2026-07-14 17:46:38.095616', '2026-06-08 13:30:30.306', 'CHARLIE'), 
 (3, '2026-06-25 18:22:42.347613', 'C:\Users\JScot\JMRI\Test_Profile.jmri\roster.xml', '2026-07-14 17:58:11.781257', '2026-07-14 17:57:17.255', 'CHARLIE');
-- sync
Insert into DECODER(ID, DECODERID, FILENAME, ROADNUMBER, ROADNAME, MANUFACTURER, OWNER, MODEL, DCCADDRESS, MANUFACTURERID, PRODUCTID, DECODERDATE, DATEIMPORTED, DATEUPDATED, DETAILTIME, DECODERTYPEID, ROSTERID, CVVERSION, LABELVERSION, FUNCTIONVERSION, KEYVERSION, SHUNT) values 
 (1, '1678 PRR B6sb', '1678_PRR_B6sb.xml', '1678', 'PRR', 'Broadway Limited', 'jsw', null, '1678', null, '1667', null, null, '2025-10-11 10:29:19.418', '2026-07-14 17:47:19.909535', 1, 1, 0, 0, 0, 0, null), 
 (143, 'DH126PS - numeric', 'DH126PS___numeric.xml', '10000', 'XXX', '', 'jsw', null, '1000', null, '', null, null, '2026-02-10 22:29:44.255', '2026-07-14 17:26:15.810189', 37, 3, 0, 0, 0, 0, null), 
 (144, 'DH126PS - with alpha', 'DH126PS___with_alpha.xml', 'A1001', 'xxx', '', 'jsw', null, '1001', null, '', null, null, '2026-02-10 22:29:44.255', '2026-07-14 17:26:15.810189', 37, 3, 0, 0, 0, 0, null), 
 (145, 'TCS WOW SS4', 'TCS_WOW_SS4.xml', '', '', '', 'jsw', null, '1200', null, '1155', null, null, '2026-06-22 12:48:05.262', '2026-07-14 17:26:15.810189', 38, 3, 0, 0, 0, 0, null), 
 (146, 'Test ESU', 'Test_ESU.xml', '', '', '', 'jsw', null, '127', null, '33554582,33554679,33554650', null, null, '2026-06-22 12:48:05.262', '2026-07-14 17:26:15.810189', 4, 3, 0, 0, 0, 0, null), 
 (2, '2004', '2004.xml', '2004', 'PRR', 'Broadway Limited', 'jsw', null, '2004', null, '', null, null, '2023-10-13 13:21:19.316', '2026-07-14 17:47:19.909535', 2, 1, 0, 0, 0, 0, null), 
 (3, '2008 PRR Shark', '2008_PRR_Shark.xml', '', '', '', 'jsw', null, '2008', null, '', null, null, '2019-08-11 17:17:23.0', '2026-07-14 17:47:19.909535', 3, 1, 0, 0, 0, 0, null);
-- sync
Insert into CVVALUES(ID, DECODERID, CVVALUE, CVNUMBER) values 
 (249812, 143, '0', '1'), 
 (249813, 143, '195', '17'), 
 (249814, 143, '232', '18'), 
 (249815, 143, '32', '29'), 
 (249816, 143, '0', '2'), 
 (249817, 143, '0', '5'), 
 (249819, 143, '30', '3'), 
 (249820, 143, '0', '4'), 
 (249821, 143, '0', '7'), 
 (249822, 143, '129', '8'), 
 (249823, 143, '0', '9'), 
 (249824, 143, '0', '19'), 
 (249825, 143, '0', '21'), 
 (249826, 143, '0', '22'), 
 (249827, 143, '1', '33'), 
 (249828, 143, '2', '34'), 
 (249829, 143, '0', '35'), 
 (249830, 143, '0', '36'), 
 (249831, 143, '0', '37'), 
 (249832, 143, '0', '49'), 
 (249833, 143, '0', '50'), 
 (249834, 143, '0', '51'), 
 (249835, 143, '0', '52'), 
 (249836, 143, '0', '54'), 
 (249837, 143, '128', '55'), 
 (249838, 143, '48', '56'), 
 (249839, 143, '6', '57'), 
 (249840, 143, '2', '61'), 
 (249841, 143, '0', '62'), 
 (249842, 143, '0', '63'), 
 (249843, 143, '0', '16'), 
 (249844, 143, '0', '65'), 
 (249845, 143, '0', '66'), 
 (249846, 143, '0', '67'), 
 (249847, 143, '9', '68');
Insert into CV_VERSIONS(DECODERID, VERSION_NUMBER, CREATED_ON) values 
 (143, 1, '2026-07-14 17:21:27.358342'), 
 (143, 2, '2026-07-14 17:26:15.810189'), 
 (144, 1, '2026-07-14 17:21:27.358342'), 
 (144, 2, '2026-07-14 17:26:15.810189'), 
 (145, 1, '2026-07-14 17:16:10.087057'), 
 (145, 2, '2026-07-14 17:26:15.810189'), 
 (146, 1, '2026-07-14 17:16:10.087057');
Insert into CVVALUES(ID, DECODERID, CVVALUE, CVNUMBER) values 
 (249848, 143, '18', '69'), 
 (249849, 143, '28', '70'), 
 (249850, 143, '37', '71'), 
 (249851, 143, '47', '72'), 
 (249852, 143, '56', '73'), 
 (249853, 143, '66', '74'), 
 (249854, 143, '75', '75'), 
 (249855, 143, '85', '76'), 
 (249856, 143, '94', '77'), 
 (249857, 143, '103', '78'), 
 (249858, 143, '113', '79'), 
 (249859, 143, '122', '80'), 
 (249860, 143, '132', '81'), 
 (249861, 143, '141', '82'), 
 (249862, 143, '151', '83'), 
 (249863, 143, '160', '84'), 
 (249864, 143, '170', '85'), 
 (249865, 143, '179', '86'), 
 (249866, 143, '188', '87'), 
 (249867, 143, '198', '88'), 
 (249868, 143, '207', '89'), 
 (249869, 143, '217', '90'), 
 (249870, 143, '226', '91'), 
 (249871, 143, '236', '92'), 
 (249872, 143, '245', '93'), 
 (249873, 143, '255', '94'), 
 (249874, 143, '0', '95'), 
 (249875, 143, '0', '105'), 
 (249876, 143, '0', '106'), 
 (249877, 144, '127', '1'), 
 (249878, 144, '195', '17'), 
 (249879, 144, '233', '18'), 
 (249880, 144, '32', '29'), 
 (249881, 144, '0', '2'), 
 (249882, 144, '0', '5');
Insert into FUNCTIONLABELS(ID, DECODERID, FUNCTIONNUMBER, FUNCTIONLABEL, LOCKED) values 
 (1561, 146, '0', 'Light', true), 
 (1564, 143, '0', 'Lights and abc', true), 
 (1566, 143, '2', 'Bell zzzz', true), 
 (1567, 144, '0', 'Lights', true), 
 (1572, 144, '3', 'new item', true), 
 (1575, 146, '1', 'new test', true), 
 (1583, 143, '3', 'new function', true), 
 (1584, 145, '0', 'lights', true), 
 (1585, 145, '1', 'horn', true), 
 (1586, 145, '2', 'additional', true);
Insert into KEYVALUES(ID, DECODERID, PAIR_KEY, PAIR_VALUE) values 
 (342, 144, 'RosterGroup:group1', 'yes'), 
 (344, 144, 'RosterGroup:group3', 'yes'), 
 (345, 145, 'RosterGroup:test2', 'yes');
Insert into CVVALUES(ID, DECODERID, CVVALUE, CVNUMBER) values 
 (249883, 144, '0', '6'), 
 (249884, 144, '0', '3'), 
 (249885, 144, '0', '4'), 
 (249886, 144, '0', '7'), 
 (249887, 144, '129', '8'), 
 (249888, 144, '0', '9'), 
 (249889, 144, '0', '19'), 
 (249890, 144, '0', '21'), 
 (249891, 144, '0', '22'), 
 (249892, 144, '1', '33'), 
 (249893, 144, '2', '34'), 
 (249894, 144, '0', '35'), 
 (249895, 144, '0', '36'), 
 (249896, 144, '0', '37'), 
 (249897, 144, '0', '49'), 
 (249898, 144, '0', '50'), 
 (249899, 144, '0', '51'), 
 (249900, 144, '0', '52'), 
 (249901, 144, '0', '54'), 
 (249902, 144, '128', '55'), 
 (249903, 144, '48', '56'), 
 (249904, 144, '6', '57'), 
 (249905, 144, '0', '61'), 
 (249906, 144, '0', '62'), 
 (249907, 144, '0', '63'), 
 (249908, 144, '0', '16'), 
 (249909, 144, '0', '65'), 
 (249910, 144, '0', '66'), 
 (249911, 144, '0', '67'), 
 (250161, 145, '64', '3'), 
 (250162, 145, '96', '4'), 
 (250342, 146, '32', '3'), 
 (250343, 146, '15', '4'), 
 (252354, 143, '0', '6');
Insert into LABEL_VERSIONS(DECODERID, VERSION_NUMBER, CREATED_ON) values 
 (143, 1, '2026-06-26 12:37:36.338674'), 
 (143, 2, '2026-06-26 15:25:12.614887'), 
 (143, 3, '2026-07-11 10:51:47.913959'), 
 (143, 4, '2026-07-13 18:20:59.371898'), 
 (144, 1, '2026-06-27 18:27:19.304604'), 
 (144, 2, '2026-07-13 18:20:59.371898'), 
 (146, 1, '2026-06-26 14:47:31.352884'), 
 (146, 2, '2026-07-11 10:55:38.48779');
-- sync
Insert into CV_DIFF(DECODERID, VERSION_NUMBER, CVNUMBER, OLD_VALUE, NEW_VALUE) values 
 (143, 2, '3', '0', '30'), 
 (143, 1, '6', null, '0'), 
 (143, 2, '61', '0', '2'), 
 (144, 1, '150', '0', null), 
 (144, 2, '160', '99', null), 
 (145, 1, '3', '32', '16'), 
 (145, 2, '3', '16', '64'), 
 (145, 1, '4', '96', '48'), 
 (145, 2, '4', '48', '96'), 
 (146, 1, '3', '64', '32'), 
 (146, 1, '4', '30', '15');
Insert into LABEL_DIFF(DECODERID, VERSION_NUMBER, FUNCTION_NUMBER, OLD_VALUE, NEW_VALUE, OLD_LOCKED, NEW_LOCKED) values 
 (143, 1, '1', 'Horn', 'Horn xxxxx', false, false), 
 (143, 1, '2', 'Bell', 'Bell yyyyy', true, true), 
 (143, 2, '0', 'Lights', 'Lights and abc', true, true), 
 (143, 2, '2', 'Bell yyyyy', 'Bell zzzz', true, false), 
 (143, 2, '3', null, 'added one here', null, true), 
 (143, 3, '1', 'Horn xxxxx', 'Horn ', false, false), 
 (143, 3, '3', 'added one here', null, true, null), 
 (143, 3, '4', null, 'additional', null, null), 
 (143, 4, '1', 'Horn ', null, false, null), 
 (143, 4, '2', 'Bell zzzz', 'Bell zzzz', false, true), 
 (143, 4, '3', null, 'new function', null, null), 
 (143, 4, '4', 'additional', null, true, null), 
 (144, 1, '1', null, null, true, null), 
 (144, 1, '2', 'Horn', 'Horn xxxx', false, false), 
 (144, 1, '3', null, 'new item', null, true), 
 (144, 2, '2', 'Horn xxxx', null, false, null), 
 (146, 1, '1', null, null, true, null), 
 (146, 1, '2', null, null, false, null), 
 (146, 2, '1', null, 'new test', null, null);
-- sync

-- Vital times
--   Collecting: 00:00:00.6
--   Exporting:  00:00:00.4
--   Total:      00:00:01.1
