= RRDecoder Documentation

== Introduction
This is the documentation for the Model Railroad Decoder Database program. The purpose of the
program is to store one or more JMRI "rosters", and all of the values for the decoders listed therein (including
their CV values). If you only have one JMRI instance containing decoders, that's fine -- you will only see the
one line in the main roster view, but you can drill down into that roster. The data is stored in a relational
database -- H2 (the software for that is included with this program).

If you have more than one JMRI instance, you can add each of them to this database. You can examine
the contents of one roster, or you can compare the contents of one roster against another. You can even
compare CV values a decoder in one roster against those in a different roster.

== Installation
There is no installation program. Simply download the zip file and unzip to an empty directory.
All the required elements (except Java) have been included in the zip file. Java is required, but
you can use Java 11 (the same as JMRI requires) or you can use Java 8.

== Running the Program
Open a terminal window (Command Prompt) and change to the directory containing the extracted program.
Change into the "bin" directory, or open an Explorer window and change to the bin directory of the extracted
program. For Windows, execute the "decoder.bat" file, or for Mac or Linux, use the "decoder" file.

== The First time - Setting the Database Values
The very first time you run the program, you must select a location for the database.
Since the database location is empty, the program will open directly into a "Preferences" window to
allow you to select the database specifics. You will need to supply a username and a password for the database that will be created when you save the settings. Once that database has been created, you *must* use the same username and password to access it. H2 (the database software) uses a "URL" to describe the database connection. You can let the program create the URL by entering a database name and a location. Use the "Directory" button to open an
explorer window to select a directory. The "Location" field *must* specify a complete path to the database location
(not a relative path -- a requirement of the H2 software).

Once you have entered all the required elements (Username, password, database name and location, or database URL),
the "Save & Close" button will be enabled. At that point the information entered will be validated (this will
also create the database). Since the program must restart to use the new database information, you will be
presented with a dialog letting you know that the program must restart. When you click the "Okay" button, the
program will end. The database information will be saved in a ".properties" file. If any errors are detected
when the program validates the data, an error message will be shown and the properties file will not be saved.
The preferences window will continue to be shown, allowing you correct the error.

[dicsrete]
== Note
The properties file is not encrypted and the username and password are clearly visible to anyone examining
that file. Since this database is not exposed to the internet and cannot modify the decoder contents, this should
not be a concern.

== Reading a Profile